#spring
spring:
  application:
    name: boot-oauth2-server
  datasource:
    url: jdbc:mysql://47.99.216.57:3306/boot-rbac?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.99.216.57
    port: 6379
  elasticsearch:
    rest:
       uris: http://47.99.216.57:9200
       connection-timeout: 3000


# security 配置
security:
  url:
#  登录 URL
    loginUrl: /login.html
#    免认证静态资源路径
    anonResourcesUrl: /swagger-resources/**,/swagger-ui.html/,v2/api-docs,/webjars/**
#    记住我超时时间
    rememberMeTimeout: 30000
#    登出 URL
    logoutUrl: /logout
#    主页 URL
    indexUrl: /index
    authUrl: /auth/login
  basic:
#    false：禁用权限
    enabled: true
  oauth2:
    resource:
      filter-order: 80



# eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
