server:
  port: 8084

spring:
  application:
    name: cloud-gateway




---
spring:
  cloud:
    gateway:
      routes:
#      唯一标识
      - id: add_request_header_route
#      路由到哪里的地址
        uri: http://httpbin.org:80/get

        filters:
        - AddRequestHeader=X-Request-Foo, Bar
        #        被解析成PredicateDefinition对象 （name =After ，args= 2017-01-20T17:42:47.789-07:00[America/Denver]）
        #         predicates的After这个配置，遵循的契约大于配置的思想，它实际被AfterRoutePredicateFactory这个类所处理，
        #          这个After就是指定了它的Gateway web handler类为AfterRoutePredicateFactory
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: add_request_header_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: add_response_header_route
        uri: http://httpbin.org:80/get
        filters:
        - AddResponseHeader=X-Response-Foo, Bar
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: add_response_header_route


---
spring:
  cloud:
    gateway:
      routes:
      - id: rewritepath_route
        uri: https://blog.csdn.net
        predicates:
        - Path=/foo/**
        filters:
        - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route

---




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/