server:
  port: 8080
  servlet:
    context-path: /cloud-movie
#spring
spring:
  application:
    name: cloud-movie

  profiles:
    active: dev
  #    新的bean允许覆盖
  main:
    allow-bean-definition-overriding: true
  #    flyway相关配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1.1.0
