
# 注册中心地址
server:
  port: 8083

spring:
  application:
    name: cloud-zuul
#  datasource:
#    url: jdbc:mysql://localhost:3306/commons?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver

# eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/


zuul:
  routes:
    api:
        path: /**
        serviceId: www.baidu.com
#        serviceId: boot-oauth2-client