
server:
  port: 8081
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
spring:
  application:
    name: cloud-movie-job
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-version: 1.1.0
##数据源配置
  datasource:
    rbac:
      url: jdbc:mysql://47.99.216.57:3306/cloud-movie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
    cloud-movie:
      url: jdbc:mysql://47.99.216.57:3306/cloud-movie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
cloud:
  crawl:
    kafka:
      bootstrap-servers: 192.168.56.103:9092,192.168.56.106:9092,192.168.56.107:9092
      session-timeout-ms: 15000
      group-id: cloud-crawl

