DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '名称',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	status INT(11) NULL DEFAULT NULL COMMENT '状态',
	creator_code VARCHAR(30) NULL DEFAULT NULL COMMENT '创建人',
	updater_code VARCHAR(30) NULL DEFAULT NULL COMMENT '更新人',
	create_time BIGINT(20) NOT NULL COMMENT '创建时间',
	update_time BIGINT(20) NOT NULL COMMENT '更新时间',
	PRIMARY KEY (id)
);
