server:
  port: 8081

boot:
  security:
    oauth2:
      client:
        serverUri: http://localhost:8080/
        clientUri: http://localhost:8081/
        clientId: boot-oauth2
        clientSecret: oauth2
        grantType: authorization_code

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commons?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: boot-oauth2-client

# cloud相关配置
feign:
  hystrix:
    enabled: true
