ALTER TABLE template_page
  ADD COLUMN key_xpath VARCHAR(255) DEFAULT NULL;
ALTER TABLE template_page
  ADD COLUMN key_regex VARCHAR(255) DEFAULT NULL;
ALTER TABLE template_field
  ADD COLUMN regex VARCHAR(255) DEFAULT NULL;