
# 注册中心地址
server:
  port: 8088


eureka:
  instance:
    hostname: localhost
  client:
#  表明为server
    registerWithEureka: false
    fetchRegistry: false
#    所有注册到的client都需要这个地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server
